services:
  - type: web
    name: owe-me-api
    runtime: image
    region: frankfurt
    plan: free
    image:
      url: ghcr.io/mrd4rkne/owe-me-api/owe-me-api:1.0.28-g3ef66ae218
    envVars:
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Database__RunMigrations
        value: "true"
      - fromGroup: dotnet-app-defaults
