services:
  - type: web
    name: owe-me-api
    runtime: docker
    region: frankfurt
    plan: free
    image:
      url: ghcr.io/mrd4rkne/owe-me-api:1.0.28-g3ef66ae218
    envVars:
      - key: Database__ConnectionString
        fromDatabase:
          name: owe-me-db
          property: connectionString
      - key: Database__RunMigrations
        value: "true"
      - fromGroup: dotnet-app-defaults

databases:
  - name: owe-me-db
    region: frankfurt
    plan: free
