services:
  oweme.api:
    image: oweme.api
    build:
      context: .
      dockerfile: OweMe.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dotnet.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1qaz@WSX
    volumes:
      - ~/.aspnet/https:/https:ro
  oweme.seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:5341"
      - "9001:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./seq:/data