services:
  oweme.api:
    image: oweme.api
    build:
      context: .
      dockerfile: OweMe.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
        - ASPNETCORE_URLS=https://+:8081;http://+:8080