name: build-release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: true
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    secrets: inherit
