name: build-regular

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

permissions: 
  contents: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: false
    secrets: inherit
