name: build-release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  checks: write
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: true
      release: ${{ github.ref == 'refs/heads/master' }}
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
