name: build-and-test

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish artifacts after build'
        required: false
        default: false
        type: boolean
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_PROJECT_KEY:
        required: true
      SONAR_ORG:
        required: true

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish artifacts after build'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

env:
  PUBLISH_ARTIFACT: "oweme-api"
  SOLUTION_PATH: "./OweMe.Api.sln"
  API_PROJECT_PATH: "./api/src/OweMe.Api"
  PUBLISH_DIR: "./publish"
  CACHE_DIR: "$HOME/.sonar"
  JAVA_VERSION: "17"

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for SonarCloud analysis and Nbgv versioning

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          # Create the cache directory if it doesn't exist
          mkdir -p ${{ env.CACHE_DIR }}/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ${{ env.CACHE_DIR }}/scanner

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Install dotcover
        run: dotnet tool install --global JetBrains.dotCover.CommandLineTools

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - uses: dotnet/nbgv@master
        id: nbgv

      - name: Get version
        run: echo "${{ steps.nbgv.outputs.SemVer2 }}"

      - name: SonarQube Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          scannerPath="$CACHE_DIR/scanner/dotnet-sonarscanner"

          # Run SonarScanner Begin with quality gate waiting enabled
          "$scannerPath" begin /k:"$SONAR_PROJECT_KEY" \
            /o:"$SONAR_ORG" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.qualitygate.timeout=300

      - name: Dotnet restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: |
          dotCover cover-dotnet \
            --reportType=HTML \
            --AttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute \
            --Output=dotCover.Output.html \
          -- test --configuration Release --no-restore --no-build --verbosity normal --filter "FullyQualifiedName!~SmokeTests"

      - name: Dotnet publish
        if: ${{ inputs.publish == true }}
        run: |
          dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Upload publish artifacts
        id: upload_artifacts
        if: ${{ inputs.publish == true }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PUBLISH_ARTIFACT }}-${{ steps.nbgv.outputs.SemVer2 }}
          path: '${{ vars.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Set artifact ID
        id: set_artifact_id
        if: ${{ inputs.publish == true }}
        run: echo "artifact_id=${{ steps.upload_artifacts.outputs.artifact-id }}" >> $GITHUB_OUTPUT

      - name: SonarQube End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          scannerPath="$CACHE_DIR/scanner/dotnet-sonarscanner"
          
          # Run SonarScanner End securely
          "$scannerPath" end /d:sonar.token="$SONAR_TOKEN"
