name: build-release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  checks: write
  pull-requests: write

environment: production

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: true
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      artifact_id: ${{ needs.build.outputs.artifact_id }}
