name: build-verification

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: false