name: build-verification

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    with:
      publish: false
    secrets: inherit
