name: build-and-test

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish artifacts after build'
        required: false
        default: false
        type: boolean
    secrets:
      SONAR_TOKEN:
          required: true
      SONAR_HOST_URL:
          required: true
      SONAR_PROJECT_KEY:
          required: true
      SONAR_ORG:
          required: true
    outputs:
      release_tag:
        description: 'Release tag from build job'
        value: ${{ jobs.build.outputs.release_tag }}
  
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish artifacts after build'
        required: false
        default: false
        type: boolean

permissions:
    contents: write

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./api/src/OweMe.Api/publish"
  PUBLISH_ARTIFACT: "oweme-api"
  SOLUTION_PATH: "./OweMe.Api.sln"
  API_PROJECT_PATH: "./api/src/OweMe.Api"
  PUBLISH_DIR: "./publish"
  CACHE_DIR: "$HOME/.sonar"

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_release_tag.outputs.tag_name }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for SonarCloud analysis and Nbgv versioning

      - name: Define Cache Directory Variable
        run: echo "CACHE_DIR=$HOME/.sonar" >> $GITHUB_ENV

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          # Create the cache directory if it doesn't exist
          mkdir -p ${{ env.CACHE_DIR }}/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ${{ env.CACHE_DIR }}/scanner

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Install dotcover
        run: dotnet tool install --global JetBrains.dotCover.CommandLineTools

      - name: Setup docker
        uses: docker/setup-buildx-action@v3
        
      - uses: dotnet/nbgv@master
        id: nbgv
        
      - name: Get version
        run: echo "${{ steps.nbgv.outputs.SemVer2 }}"

      - name: SonarQube Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          scannerPath="$CACHE_DIR/scanner/dotnet-sonarscanner"

          # Run SonarScanner Begin with quality gate waiting enabled
          "$scannerPath" begin /k:"$SONAR_PROJECT_KEY" \
            /o:"$SONAR_ORG" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.qualitygate.timeout=300

      - name: Dotnet restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: |
          dotCover cover-dotnet \
            --reportType=HTML \
            --AttributeFilters=System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute \
            --Output=dotCover.Output.html \
          -- test --configuration Release --no-restore --no-build --verbosity normal

      - name: Dotnet publish
        if: ${{ inputs.publish == true }}
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}
        
      - name: Set output for release tag
        if: ${{ inputs.publish == true }}
        run: echo "tag_name=${{ steps.nbgv.outputs.SemVer2 }}" >> $GITHUB_OUTPUT
        id: set_release_tag
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: ${{ inputs.publish == true }}
        with:
          name: ${{ env.PUBLISH_ARTIFACT }}-${{ steps.nbgv.outputs.SemVer2 }}
          tag_name: ${{ steps.set_release_tag.outputs.tag_name }}
          target_commitish: ${{ github.ref }}
          generate_release_notes: true
          files: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/**
          prerelease: ${{ contains(steps.nbgv.outputs.SemVer2, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: SonarQube End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
        run: |
          scannerPath="$CACHE_DIR/scanner/dotnet-sonarscanner"
          
          # Run SonarScanner End securely
          "$scannerPath" end /d:sonar.token="$SONAR_TOKEN"