name: Run Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

env:
  SMOKETESTS_FOLDER_PATH: "./api/tests/OweMe.Api.SmokeTests"
  CSPROJ_NAME: "OweMe.Api.SmokeTests.csproj"

jobs:
  test:
    name: Run smoke tests
    runs-on: ubuntu-latest
    env:
      CSPROJ_PATH: "${{ env.SMOKETESTS_FOLDER_PATH }}/${{ env.CSPROJ_NAME }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for Nbgv versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Update settings.json
        run: |
          echo "${{ secrets.SMOKETESTS_APPSETTINGS }}" | tee "${{ env.SMOKETESTS_FOLDER_PATH}}/appsettings.json" > /dev/null && chmod 600 "${{ env.SMOKETESTS_FOLDER_PATH}}/appsettings.json"

      - name: Restore dependencies
        run: dotnet restore "${{ env.CSPROJ_PATH }}"

      - name: Build smoke tests
        run: dotnet build "${{ env.CSPROJ_PATH }}" --no-restore --configuration Release

      - name: Run smoke tests
        run: dotnet test "${{ env.CSPROJ_PATH }}" --no-build --verbosity normal