name: Run Smoke Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

env:
  SMOKETESTS_FOLDER_PATH: "./api/tests/OweMe.Api.SmokeTests"
  CSPROJ_NAME: "OweMe.Api.SmokeTests.csproj"

jobs:
  test:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for Nbgv versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Install dotcover
        run: dotnet tool install --global JetBrains.dotCover.CommandLineTools

      - name: Update settings.json
        run: |
          echo "${{ secrets.SMOKETESTS_APPSETTINGS }}" > "appsettings.json"

      - name: Restore dependencies
        working-directory: "${{ env.SMOKETESTS_FOLDER_PATH }}"
        run: dotnet restore "${{ env.CSPROJ_NAME }}"

      - name: Build smoke tests
        working-directory: "${{ env.SMOKETESTS_FOLDER_PATH }}"
        run: dotnet build "${{ env.CSPROJ_NAME }}" --no-restore --configuration Release

      - name: Run smoke tests with dotCover
        working-directory: "${{ env.SMOKETESTS_FOLDER_PATH }}"
        run: dotCover cover-dotnet --reportType=HTML --Output=dotCover.Output.html -- test "${{ env.CSPROJ_NAME }}" --configuration Release --no-restore --no-build --verbosity normal