name: Run Smoke Tests

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

permissions:
  contents: read

env:
  SMOKETESTS_FOLDER_PATH: "./api/tests/OweMe.SmokeTests"

jobs:
  test:
    name: Run smoke tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for Nbgv versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Update settings.json
        run: |
          echo "${{ secrets.SMOKETESTS_APPSETTINGS }} > "${{ env.SMOKETESTS_FOLDER_PATH}}/appsettings.json"

      - name: Restore dependencies
        run: dotnet restore "${{ env.SMOKETESTS_FOLDER_PATH}}/OweMe.SmokeTests.csproj"

      - name: Build smoke tests
        run: dotnet build "${{ env.SMOKETESTS_FOLDER_PATH}}/OweMe.SmokeTests.csproj" --no-restore --configuration Release

      - name: Run smoke tests
        run: dotnet test "${{ env.SMOKETESTS_FOLDER_PATH}}/OweMe.SmokeTests.csproj" --no-build --verbosity normal